SILA-4085: Integrated Generate Processor Token using Create Plaid Account flow has been completed.
Sila-Money/sila-sdk-demo pull request #179
Opened 2022-04-25 14:16 UTC by ArcGate-Vinod

Hi @amack300,

Integrated `Generate Processor Token` using `Create Plaid Account` flow has been completed.

Thanks!

2022-04-27 14:21 UTC, amack300 commented on src/components/accounts/GenerateProcessorComponents.js
> +  const DEFAULT_PROCESSOR_NAME = 'sila_money';
Hey @ArcGate-Vinod can we move this into constants?

2022-04-27 14:22 UTC, amack300 commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({accessToken: "This field may not be blank."}, validationErrors);
Hey @ArcGate-Vinod, can we use the spread operator instead?  {... validationErrors, accessToken: "__MESSAGE__" }

2022-04-27 14:22 UTC, amack300 commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({accountId: "This field may not be blank."}, validationErrors);
Hey @ArcGate-Vinod, can we use the spread operator instead?  {... validationErrors, accessToken: "__MESSAGE__" }

2022-04-27 14:23 UTC, amack300 commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({processorName: "This field may not be blank."}, validationErrors);
Hey @ArcGate-Vinod, can we use the spread operator instead?  {... validationErrors, processorName: "__MESSAGE__" }

2022-04-27 14:23 UTC, amack300 commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({processorToken: "This field may not be blank."}, validationErrors);
Hey @ArcGate-Vinod, can we use the spread operator instead?  {... validationErrors, processorToken: "__MESSAGE__" }

2022-04-27 14:24 UTC, amack300 commented on src/components/accounts/GenerateProcessorComponents.js
> +export const plaidSignUpSteps = [{
Hey @ArcGate-Vinod, can we move this into a separate file in constnants.js and import it.  Something like constants/plaidSignUpSteps.js

2022-04-27 14:25 UTC, amack300 commented on src/views/Accounts.js
> +  const DEFAULT_GP_ROUTES = [{
Hey @ArcGate-Vinod, can we move this into constants file and import it?

2022-04-27 14:30 UTC, amack300 commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({secretKey: "This field may not be blank."}, validationErrors);
Hey @ArcGate-Vinod, can we use the spread operator instead?  {... validationErrors, secretKey: "__MESSAGE__" }

2022-04-27 14:35 UTC, amack300 commented on src/components/accounts/GenerateProcessorComponents.js
> +    {context && context.map((option, index) => <p key={index} className="text-muted mb-3" dangerouslySetInnerHTML={{ __html: option.link && option.content ? option.content.replace(option.link, `<a hr
Hey @ArcGate-Vinod, I am not exactly sure what's going on here, but is there a way we can avoid using dangerouslySetInnerHTML.  Please try and avoid using this flag as it can have security issues.

2022-04-27 14:37 UTC, amack300 requested changes
Hey @ArcGate-Vinod, I provided some feedback, it's mainly just some clean up.  Great work!

2022-04-28 11:28 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +  const DEFAULT_PROCESSOR_NAME = 'sila_money';
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:28 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({accessToken: "This field may not be blank."}, validationErrors);
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:28 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({accountId: "This field may not be blank."}, validationErrors);
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:28 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({processorName: "This field may not be blank."}, validationErrors);
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:28 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({processorToken: "This field may not be blank."}, validationErrors);
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:28 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +export const plaidSignUpSteps = [{
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:28 UTC, ArcGate-Vinod commented on src/views/Accounts.js
> +  const DEFAULT_GP_ROUTES = [{
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:28 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({clientId: "This field may not be blank."}, validationErrors);
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:29 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +      validationErrors = Object.assign({secretKey: "This field may not be blank."}, validationErrors);
Hi @amack300,
This change has been addressed.
Thanks

2022-04-28 11:29 UTC, ArcGate-Vinod commented on src/components/accounts/GenerateProcessorComponents.js
> +    {context && context.map((option, index) => <p key={index} className="text-muted mb-3" dangerouslySetInnerHTML={{ __html: option.link && option.content ? option.content.replace(option.link, `<a hr
Hi @amack300,

Here I need to use HTML elements dynamically in an application so I used that, FYI we have the web links in the content which need to convert into hyperlinks, and for the security concern I've sanitized using `DOMPurify` please review this - https://www.npmjs.com/package/dompurify

Thanks!

2022-04-29 20:33 UTC, amack300 approved these changes
LGTM

2022-05-02 07:26 UTC, merged